version: '3.8'

services:
  gptcodetranslator:
    build: .
    ports:
      - 3002:3002
    environment:
      - OPENAI_API_KEY
      - DEFAULT_MODEL
      - NEXT_PUBLIC_DEFAULT_SYSTEM_PROMPT
      - AZURE_DEPLOYMENT_ID
      - OPENAI_API_VERSION
      - OPENAI_API_TYPE
      - OPENAI_API_HOST
    env_file:
      - .env.local
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
