version: '3.8'

services:
  aicodetranslator:
    build: .
    container_name: aicodetranslator
    ports:
      - '3002:3002'
    volumes:
      - .:/app
      - /app/node_modules
      - ./env.local:/app/.env.local
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: always
    security_opt:
      - no-new-privileges:true
